/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myErc721MintByIdSol from "./MyERC721MintByID.sol";
export type { myErc721MintByIdSol };
export type { NumberGuessingGame } from "./NumberGuessingGame";
