/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErc721MintByIdSol from "./MyERC721MintByID.sol";
export { NumberGuessingGame__factory } from "./NumberGuessingGame__factory";
