/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as operatorAllowlistSol from "./OperatorAllowlist.sol";
export { IOperatorAllowlist__factory } from "./IOperatorAllowlist__factory";
